config/routes.rb
Rails.application.routes.draw do
  resources :metric_reports

  resources :metrics

  root 'home#index'

end

app/models/metric.rb
require 'csv'
class Metric < ActiveRecord::Base

	class << self

		def import_csv(file=nil)
			csv_data = nil
			begin
				storage = Fog::Storage.new(
					provider: ENV['FOG_PROVIDER'],
					aws_access_key_id: ENV['AWS_ACCESS_KEY_ID'],
					aws_secret_access_key: ENV['AWS_SECRET_ACCESS_KEY']
				)
				remote_file = storage.
					directories.
					find {|dir| dir.key == ENV["AWS_BUCKET"]}.
					files.
					find {|file| file.key == ENV["AWS_PATH"]}
				csv_data = remote_file.body
			rescue => e
				file ||= Rails.root.join('public', 'flowdata.csv')
				# TODO revise in the future to do in a stream fashion (not loading all to memory at once)
				csv_data = File.open(file, 'r') {|f| f.read}
			end
			data = CSV.parse(csv_data, headers: true, col_sep: "\t")
			puts 'data.inspect'
			puts data.to_a.inspect
			if (Metric.count == 0)
				import_without_validations_or_callbacks(data.headers, data.to_a.drop(1)) #drop header
			else
				data.map(&:to_hash).each do |attributes|
					Metric.find_or_create_by(attributes)
				end
			end

			# metrics = [
			# 	"TripsScheduled",
			# 	"TripsPerformed",
			# 	"TripsBilled",
			# 	"TripsPaid",
			# 	"DaysToCash",
			# 	"OnTimePerformance",
			# ]
			#
			columns = [
	            "Measurement",
				"Trend"
	        ] + months

			metric_types = ['Count', 'Dollars']
			metric_types.each do |metric_type|
				calculateTableData(metric_type).each do |summary|
					['month', 'week'].each do |period_type|
						summary[period_type].each do |key, value|
							if period_type == 'month' && key.match(/\d{4}-\d{2}/)
								date_parts = key.split('-')
								year = date_parts.first
								month = date_parts.last
								period = Date.new(year.to_i, month.to_i)
							elsif period_type == 'week'
								period = key
							end
							MetricReport.find_or_create_by(
								name: summary['Measurement'],
								period_type: period_type,
								period: period,
								value: value
							)							
						end
					end
				end
			end
		end

		private
		# TODO update naming conventions to Ruby. This was converted from JavaScript
		def thisYear
			@this_year ||= Date.current.year
		end

		def rawData
			@raw_data ||= Metric.all.map do |metric|
				attrs = metric.attributes.clone
				attrs.delete('id')
				attrs
			end.map(&:values)
		end

		def months
			@months ||= Metric.send(:rawData).map(&:first).reject {|date| date.nil?}.map {|date| "#{date.year}-#{date.month.to_s.rjust(2, padstr='0')}"}.uniq.sort
		end

		def week_ends
			@week_ends ||= Metric.send(:rawData).map(&:first).reject {|date| date.nil?}.map do |date|
				week_end(date)
			end.uniq.sort
		end

		def metrics
			@metrics ||= Metric.send(:rawData).map(&:second).reject {|metric| metric.nil?}.uniq.sort
		end

		def week_end(date)
			date + (7 - date.wday)
		end

		def calculateTableData(metricType)
			metrics.map do |metric|
				rowHash = months.reduce({'month' => {}}) do |output, month|
					accumulator = accumulate_metric_type_data_matching_period(metricType, metric) do |row|
						monthNumStr = (month.split('-').last)
						row[0].to_s.starts_with?("#{thisYear}-#{monthNumStr}-")
					end
					value = rawData.reduce(0, &accumulator)
					output['month'][month] = value != 0 && !!value ? value : 'N/A'
					output
				end
				rowHash = week_ends.reduce(rowHash.merge('week' => {})) do |output, week_end|
					accumulator = accumulate_metric_type_data_matching_period(metricType, metric) do |row|
						week_end(row[0]) == week_end
					end
					value = rawData.reduce(0, &accumulator)
					output['week'][week_end] = value != 0 && !!value ? value : 'N/A'
					output
				end
				rowHash['Measurement'] = metric.humanize + ' ('+metricType+')';
				rowHash;
			end
		end

		def accumulate_metric_type_data_matching_period(metricType, metric, &period_matcher)
			-> (outcome, row) {
				return outcome if row.empty?
				metricMatch = row[1] == metric
				metricTypeMatch = row[2] == metricType
				valueToAdd = row[4].to_f
				period_matcher.call(row) && metricMatch && metricTypeMatch ? (outcome + valueToAdd) : outcome
			}
		end


	end

end

app/models/metric_report.rb
class MetricReport < ActiveRecord::Base
  METRICS = %w(
    trips_scheduled(count)
    trips_performed(count)
    trips_billed(count)
    trips_paid(count)
    on_time_performance(count)
    trips_scheduled(dollars)
    trips_performed(dollars)
    trips_billed(dollars)
    trips_paid(dollars)
    on_time_performance(dollars)
  )

  class << self
    def names
      pluck(:name).uniq.sort {|a, b| METRICS.index(a.dehumanize) <=> METRICS.index(b.dehumanize)}
    end
    def months
      where(period_type: 'month').order(period: :asc).pluck(:period).uniq
    end
    def week_ends
      where(period_type: 'week').order(period: :asc).pluck(:period).uniq
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
	end
end

app/controllers/metric_reports_controller.rb
class MetricReportsController < ApplicationController
  before_action :set_metric_report, only: [:show, :edit, :update, :destroy]

  # GET /metric_reports
  # GET /metric_reports.json
  def index
    @metric_reports = MetricReport.all
  end

  # GET /metric_reports/1
  # GET /metric_reports/1.json
  def show
  end

  # GET /metric_reports/new
  def new
    @metric_report = MetricReport.new
  end

  # GET /metric_reports/1/edit
  def edit
  end

  # POST /metric_reports
  # POST /metric_reports.json
  def create
    @metric_report = MetricReport.new(metric_report_params)

    respond_to do |format|
      if @metric_report.save
        format.html { redirect_to @metric_report, notice: 'Metric report was successfully created.' }
        format.json { render :show, status: :created, location: @metric_report }
      else
        format.html { render :new }
        format.json { render json: @metric_report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /metric_reports/1
  # PATCH/PUT /metric_reports/1.json
  def update
    respond_to do |format|
      if @metric_report.update(metric_report_params)
        format.html { redirect_to @metric_report, notice: 'Metric report was successfully updated.' }
        format.json { render :show, status: :ok, location: @metric_report }
      else
        format.html { render :edit }
        format.json { render json: @metric_report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /metric_reports/1
  # DELETE /metric_reports/1.json
  def destroy
    @metric_report.destroy
    respond_to do |format|
      format.html { redirect_to metric_reports_url, notice: 'Metric report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_metric_report
      @metric_report = MetricReport.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def metric_report_params
      params.require(:metric_report).permit(:name, :period, :period_type, :value)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/metric_reports_helper.rb
module MetricReportsHelper
end

app/helpers/metrics_helper.rb
module MetricsHelper
end

app/views/home/index.html.erb
<h1>Emergency Transportation Business Intelligence</h1>

<table>
  <tr>
    <td>
      Value:
    </td>
    <td>
      <input id="metricType-Count" type="radio" name="metricType" value="Count" checked="checked" />
      <label for="metricType-Count">Count</label>
    </td>
    <td>
      <input id="metricType-Dollars" type="radio" name="metricType" value="Dollars" />
      <label for="metricType-Dollars">Dollars</label>
    </td>
  </tr>
  <tr>
    <td>
      Period:
    </td>
    <td>
      <input id="periodType-Week" type="radio" name="periodType" value="week" checked="checked" />
      <label for="periodType-Week">Week Ending</label>
    </td>
    <td>
      <input id="periodType-Month" type="radio" name="periodType" value="month" />
      <label for="periodType-Month">Month</label>
    </td>
  </tr>
</table>


<% ['Count', 'Dollars'].each do |metric_type| %>
  <% ['week', 'month'].each do |period_type| %>
    <div id="grid-container-<%= metric_type %>-<%= period_type %>" class="grid-container">
      <%= render 'metric_reports/metric_reports',
                  table_id_prefix: 'grid',
                  metric_type: metric_type,
                  period_type: period_type
      %>
    </div>
  <% end %>
<% end %>
<%#= image_tag "progress_bar.gif", class: 'progress-bar' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EmergencyTransportationBi</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
    <link rel="stylesheet" href="//kendo.cdn.telerik.com/2015.3.1111/styles/kendo.common-material.min.css" />
    <link rel="stylesheet" href="//kendo.cdn.telerik.com/2015.3.1111/styles/kendo.material.min.css" />

    <script src="//kendo.cdn.telerik.com/2015.3.1111/js/kendo.all.min.js"></script>  

	<script type='text/javascript'>
	(function (d, t) {
	  var bh = d.createElement(t), s = d.getElementsByTagName(t)[0];
	  bh.type = 'text/javascript';
	  bh.src = '//www.bugherd.com/sidebarv2.js?apikey=<%= ENV["BUG_HERD_API_KEY"] %>';
	  s.parentNode.insertBefore(bh, s);
	  })(document, 'script');
	</script>    
</head>
<body>

<%= yield %>

<p>Please ensure being <a href="http://www.bugherd.com/users/sign_in">signed in</a> on <a href="http://www.bugherd.com">BugHerd</a> to report issues</p>

</body>
</html>

app/views/metric_reports/_form.html.erb
<%= form_for(@metric_report) do |f| %>
  <% if @metric_report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@metric_report.errors.count, "error") %> prohibited this metric_report from being saved:</h2>

      <ul>
      <% @metric_report.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :period %><br>
    <%= f.date_select :period %>
  </div>
  <div class="field">
    <%= f.label :period_type %><br>
    <%= f.text_field :period_type %>
  </div>
  <div class="field">
    <%= f.label :value %><br>
    <%= f.text_field :value %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/metric_reports/_metric_reports.html.erb
<% @table_id_prefix = table_id_prefix rescue 'grid' %>
<% @metric_type = metric_type rescue 'Count' %>
<% @period_type = period_type rescue 'week' %>

<div class="metric-report">
  <div class="fixed">
    <table id='<%= "#{@table_id_prefix}-#{@metric_type}-#{@period_type}" %>'>
      <thead>
        <tr>
          <th>Measurement</th>
          <th>Trend</th>
        </tr>
      </thead>
      <tbody>
        <% MetricReport.names.select {|name| name.include?(@metric_type)}.each do |name| %>
        <tr>
          <td><%= name %></td>
          <td></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <div class="scrollable">
    <table id='<%= "#{@table_id_prefix}-#{@metric_type}-#{@period_type}" %>'>
      <thead>
        <tr>
          <% if @period_type == 'week' %>
          <% MetricReport.week_ends.each do |week_end| %>
          <th><%= week_end.strftime('%b %d, %Y') %></th>
          <% end %>
          <% else %>
          <% MetricReport.months.each do |month| %>
          <th><%= month.strftime('%b %Y') %></th>
          <% end %>
          <% end %>
        </tr>
      </thead>
      <tbody>
        <% MetricReport.names.select {|name| name.include?(@metric_type)}.each do |name| %>
        <tr>
          <% if @period_type == 'week' %>
          <% MetricReport.week_ends.each do |week_end| %>
          <td>
            <% value = MetricReport.find_by(period: week_end, period_type: 'week', name: name).value %>
            <% if @metric_type == 'Count' %>
            <%= number_with_precision(value, :precision => 2, :delimiter => ',') %>
            <% else %>
            <%= number_to_currency(value, :precision => 2, :delimiter => ',') %>
            <% end %>
          </td>
          <% end %>
          <% else %>
          <% MetricReport.months.each do |month| %>
          <td>
            <% value = MetricReport.find_by(period: month, period_type: 'month', name: name).value %>
            <% if @metric_type == 'Count' %>
            <%= number_with_precision(value, :precision => 2, :delimiter => ',') %>
            <% else %>
            <%= number_to_currency(value, :precision => 2, :delimiter => ',') %>
            <% end %>
          </td>
          <% end %>
          <% end %>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/metric_reports/edit.html.erb
<h1>Editing metric_report</h1>

<%= render 'form' %>

<%= link_to 'Show', @metric_report %> |
<%= link_to 'Back', metric_reports_path %>

app/views/metric_reports/index.html.erb
<h1>Listing metric_reports</h1>

<%= render 'metric_reports', table_id: 'table-Count', metric_type: 'Count' %>

<br>

<%= link_to 'New Metric report', new_metric_report_path %>

app/views/metric_reports/new.html.erb
<h1>New metric_report</h1>

<%= render 'form' %>

<%= link_to 'Back', metric_reports_path %>

app/views/metric_reports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @metric_report.name %>
</p>

<p>
  <strong>Period:</strong>
  <%= @metric_report.period %>
</p>

<p>
  <strong>Period type:</strong>
  <%= @metric_report.period_type %>
</p>

<p>
  <strong>Value:</strong>
  <%= @metric_report.value %>
</p>

<%= link_to 'Edit', edit_metric_report_path(@metric_report) %> |
<%= link_to 'Back', metric_reports_path %>